### ISSUE TITLE
您好，请问下个offiec add-in问题

### ISSUE THREAD

**Issue by qdesk** [chenxizhang/office365dev#3]
最近在研究 office online server  我想在它上面弄个add-in 插件 不知道是不是跟office365开发 add-in 一样，不知道有没有想过的资料可以让我参考下。

**Comment by jerrygaoc** [comment]
我用npm start 在本地打开了服务，是localhost:3000, 把XML文件拷贝到公共盘后，在Excel中shared folder里没有看到app 显示No add-ins currently available.请问是什么原因？难道必须要部署到内网服务器上或者必须配置HTTPS才能显示出来吗？

**Comment by chenxizhang** [comment]
新的Office 365 Add-in跟office online server没有直接关系哦，你是要做什么场景？

**Comment by chenxizhang** [comment]
根据 https://docs.microsoft.com/zh-cn/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets 这里的介绍，部分API是支持Office Online Server的，请参考

![image](https://user-images.githubusercontent.com/1996954/52521648-2ef4ab00-2cb5-11e9-9e9d-7b66e91d3237.png)
