### ISSUE TITLE
显示No add-ins currently available.

### ISSUE THREAD

**Issue by jerrygaoc** [chenxizhang/office365dev#4]
我用npm start 在本地打开了服务，是localhost:3000, 把XML文件拷贝到公共盘后，在Excel中shared folder里没有看到app 显示No add-ins currently available.请问是什么原因？难道必须要部署到内网服务器上或者必须配置HTTPS才能显示出来吗？

**Comment by chenxizhang** [comment]
不会的。可能还是因为你的路径设置不对，或者你确认一下，下面的那个勾，是否勾上了

![image](https://user-images.githubusercontent.com/1996954/52517932-174e0000-2c7e-11e9-8f12-1626f4d0fb7e.png)
