### ISSUE TITLE
关于使用Microsoft Graph 发送html邮件的问题

### ISSUE THREAD

**Issue by songshizhao** [chenxizhang/office365dev#5]
因为我把html中的图片数据内嵌到html文本当中,例如,"<"img src="data:image/png;base64,.......",这样在发送的邮件中,src属性完全丢失.,图片不能显示,这是不是无解...,请问有什么解决办法吗?非常感谢.

**Comment by chenxizhang** [comment]
不能直接用这样的方式嵌入图片，请参考 https://github.com/estruyf/Mail-Embed-Images-with-Microsoft-Graph/blob/master/ES.SendMail/Program.cs  这个做法，需要先把图片作为附件传进去，然后引用它的id
