### ISSUE TITLE
关于Office Add-in有些问题

### ISSUE THREAD

**Issue by baomihuayu** [chenxizhang/office365dev#6]
1. 网页在office中运行环境是Trident内核或者是目前流行的Blink内核
   关于上述问题是由于目前主流的前端开发基本上会采用流行的MVVM框架，MVVM框架可能有些新特性在Trident中不适用以及在流行的第三方库可能也会存在某些属性在Trident内核中不适用的情况
2. 如何在word,excel,powerpoint中采用类似Browser中的F12调试工具，可以可视化对页面DOM拾取，查看console输出

**Comment by chenxizhang** [comment]
@baomihuayu 不好意思，之前没有留意到这个留言。目前网页在Office中运行环境是Microsoft Edge webview2。请参考我的一个公众号文章：https://mp.weixin.qq.com/s?__biz=MjM5ODEyNjE5OA==&mid=2455456814&idx=1&sn=530a519fd803e9c18fd095352afb53bf&chksm=b1609b3786171221a6c82b66f8dad15234284b2330ddaa4fef00dd509a6c9e4558e235e8e75d#rd

**Comment by chenxizhang** [comment]
如果有进一步问题，可以通过我的一个公开的企业微信号联系我。

![56c678c82da39e636e6e72e26032f46](https://user-images.githubusercontent.com/1996954/160264499-ba268069-790f-4f23-9a7c-b2991b510238.jpg)
